// Generated by scripts/embed-models.mjs. Do not edit by hand.
// Canonical source: python/tokenmaster/src/tokenmaster/data/models.json
// Regenerate with: npm run embed:models
export const MODELS_DATA: unknown = {
  "schema_version": "0.1",
  "snapshot_date": "2026-07-07",
  "models": [
    {
      "model_id": "anthropic:claude-fable-5",
      "provider": "anthropic",
      "aliases": [],
      "window_nominal": 1000000,
      "max_output": 128000,
      "pricing": {
        "input": 10,
        "output": 50,
        "cache_read": 1,
        "cache_write": 12.5,
        "currency": "USD",
        "as_of": "2026-07-07"
      },
      "tokenizer_hint": "claude-2026",
      "source": "platform.claude.com pricing docs and OpenRouter, 2026-07-07; cache_write is the 5-minute rate (1.25x input)"
    },
    {
      "model_id": "anthropic:claude-opus-4-8",
      "provider": "anthropic",
      "aliases": [],
      "window_nominal": 1000000,
      "max_output": null,
      "pricing": {
        "input": 5,
        "output": 25,
        "cache_read": 0.5,
        "cache_write": 6.25,
        "currency": "USD",
        "as_of": "2026-07-07"
      },
      "tokenizer_hint": "claude-2026",
      "source": "platform.claude.com pricing docs and July 2026 trackers; cache_write is the 5-minute rate (1.25x input)"
    },
    {
      "model_id": "anthropic:claude-sonnet-5",
      "provider": "anthropic",
      "aliases": [],
      "window_nominal": 1000000,
      "max_output": null,
      "pricing": {
        "input": 2,
        "output": 10,
        "cache_read": 0.2,
        "cache_write": 2.5,
        "currency": "USD",
        "as_of": "2026-07-07"
      },
      "tokenizer_hint": "claude-2026",
      "source": "introductory pricing through 2026-08-31, then 3.0/15.0; platform.claude.com pricing docs; cache_write is the 5-minute rate (1.25x input)"
    },
    {
      "model_id": "anthropic:claude-sonnet-4-6",
      "provider": "anthropic",
      "aliases": [],
      "window_nominal": 1000000,
      "max_output": null,
      "pricing": {
        "input": 3,
        "output": 15,
        "cache_read": 0.3,
        "cache_write": 3.75,
        "currency": "USD",
        "as_of": "2026-07-07"
      },
      "tokenizer_hint": "claude-legacy",
      "source": "platform.claude.com pricing docs; 1M context at standard pricing per Anthropic model list; cache_write is the 5-minute rate (1.25x input)"
    },
    {
      "model_id": "anthropic:claude-haiku-4-5",
      "provider": "anthropic",
      "aliases": [],
      "window_nominal": 200000,
      "max_output": null,
      "pricing": {
        "input": 1,
        "output": 5,
        "cache_read": 0.1,
        "cache_write": 1.25,
        "currency": "USD",
        "as_of": "2026-07-07"
      },
      "tokenizer_hint": "claude-legacy",
      "source": "platform.claude.com pricing docs and July 2026 trackers; cache_write is the 5-minute rate (1.25x input)"
    },
    {
      "model_id": "openai:gpt-5.5",
      "provider": "openai",
      "aliases": [],
      "window_nominal": 1050000,
      "max_output": 128000,
      "pricing": {
        "input": 5,
        "output": 30,
        "cache_read": 0.5,
        "cache_write": 0,
        "currency": "USD",
        "as_of": "2026-07-07"
      },
      "tokenizer_hint": null,
      "source": "developers.openai.com model page, 2026; long-context surcharge above 272K input (2x input, 1.5x output) not modeled in flat pricing; OpenAI charges no cache-write fee"
    },
    {
      "model_id": "openai:gpt-5.4",
      "provider": "openai",
      "aliases": [],
      "window_nominal": 1050000,
      "max_output": 128000,
      "pricing": {
        "input": 2.5,
        "output": 15,
        "cache_read": 0.25,
        "cache_write": 0,
        "currency": "USD",
        "as_of": "2026-07-07"
      },
      "tokenizer_hint": null,
      "source": "developers.openai.com model page, 2026; long-context surcharge above 272K input (2x input, 1.5x output) not modeled in flat pricing; OpenAI charges no cache-write fee"
    },
    {
      "model_id": "openai:gpt-5.4-mini",
      "provider": "openai",
      "aliases": [],
      "window_nominal": 400000,
      "max_output": null,
      "pricing": {
        "input": 0.75,
        "output": 4.5,
        "cache_read": 0.075,
        "cache_write": 0,
        "currency": "USD",
        "as_of": "2026-07-07"
      },
      "tokenizer_hint": null,
      "source": "OpenAI pricing trackers, June 2026; cache_read assumed at the 10 percent pattern, unverified; OpenAI charges no cache-write fee"
    },
    {
      "model_id": "openai:gpt-5.2",
      "provider": "openai",
      "aliases": [],
      "window_nominal": 400000,
      "max_output": 128000,
      "pricing": {
        "input": 1.75,
        "output": 14,
        "cache_read": 0.175,
        "cache_write": 0,
        "currency": "USD",
        "as_of": "2026-07-07"
      },
      "tokenizer_hint": null,
      "source": "platform.openai.com model page (previous frontier model); OpenAI charges no cache-write fee"
    },
    {
      "model_id": "google:gemini-3.1-pro",
      "provider": "google",
      "aliases": [
        "gemini-3.1-pro-preview"
      ],
      "window_nominal": 1048576,
      "max_output": null,
      "pricing": {
        "input": 2,
        "output": 12,
        "cache_read": 0.2,
        "cache_write": 0,
        "currency": "USD",
        "as_of": "2026-07-07"
      },
      "tokenizer_hint": null,
      "source": "ai.google.dev pricing, prompts up to 200K; tiered rate above 200K (4.0/18.0) not modeled in flat pricing; cache storage fees per hour not modeled; max_output reports conflict (64K vs 128K) so left null"
    },
    {
      "model_id": "google:gemini-3.5-flash",
      "provider": "google",
      "aliases": [],
      "window_nominal": 1000000,
      "max_output": 64000,
      "pricing": {
        "input": 1.5,
        "output": 9,
        "cache_read": 0.15,
        "cache_write": 0,
        "currency": "USD",
        "as_of": "2026-07-07"
      },
      "tokenizer_hint": null,
      "source": "ai.google.dev pricing, launched Google I/O May 2026; cache storage fees per hour not modeled"
    },
    {
      "model_id": "deepseek:deepseek-v4",
      "provider": "deepseek",
      "aliases": [],
      "window_nominal": 1000000,
      "max_output": null,
      "pricing": null,
      "tokenizer_hint": null,
      "source": "capacity per June 2026 cross-vendor comparisons; pricing varies by host and is omitted"
    }
  ]
};
