// Embeds the canonical model registry snapshot into a TypeScript module.
//
// Canonical source (single source of truth for all languages, 0.1 ruling):
//   python/tokenmaster/src/tokenmaster/data/models.json
//
// Embedding instead of fs.readFileSync at runtime keeps the package free of
// node:fs and node:path, so the core runs in browsers and bundlers unchanged.
// The generated module is committed; a sync test asserts JSON-equality with
// the canonical file so silent drift fails the suite.
//
// Regenerate with: npm run embed:models

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const SOURCE = new URL(
  "../../../python/tokenmaster/src/tokenmaster/data/models.json",
  import.meta.url
);
const TARGET = new URL("../src/models-data.ts", import.meta.url);

const raw = readFileSync(SOURCE, "utf8");
const data = JSON.parse(raw); // validates the JSON before embedding

const banner = [
  "// Generated by scripts/embed-models.mjs. Do not edit by hand.",
  "// Canonical source: python/tokenmaster/src/tokenmaster/data/models.json",
  "// Regenerate with: npm run embed:models",
  "",
].join("\n");

const body =
  "export const MODELS_DATA: unknown = " +
  JSON.stringify(data, null, 2) +
  ";\n";

writeFileSync(TARGET, banner + body);
console.log("embedded", fileURLToPath(SOURCE));
console.log("     into", fileURLToPath(TARGET));
